### ISSUE TITLE
Crossbell Disabled How to Activate

### ISSUE THREAD

**Issue by ethzerox** [Crossbell-Box/Crossbell-Contracts#1]
![image](https://user-images.githubusercontent.com/99235229/174425221-cebc19b6-3cd5-4242-8f14-cc673c40f9b5.png)

**Comment by Candinya** [comment]
Click to enable.
BTW please submit CrossSync related issues directly to [CrossSync Repo](https://github.com/NaturalSelectionLabs/CrossSync). Thanks.
