### ISSUE TITLE
Extend operator to an array of address

### ISSUE THREAD

**Issue by AtlasQuan** [Crossbell-Box/Crossbell-Contracts#8]
1. One possible scenario is, we may need to grant multiple parties permission to post notes on our behalf.
2. Another reasonable scenario is to have an organization character account and some members of this organization should have permission to post.

**Comment by Fooooooooooox** [comment]
added in this pr: https://github.com/Crossbell-Box/Crossbell-Contracts/pull/9 (should be available after next upgrade)
